// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  home_section: dynamic(() => import("./MainSection")),
  tiles: dynamic(() => import("./Tiles")),
};
